

CREATE TABLE TANQUES (
    ID INTEGER NOT NULL,
    DESCTANQUE VARCHAR(50) NOT NULL);

ALTER TABLE TANQUES
ADD CONSTRAINT PK_TANQUES
PRIMARY KEY (ID);

COMMIT WORK;

CREATE TABLE BOMBAS (
    ID INTEGER NOT NULL,
    ID_TANQUE INTEGER NOT NULL,
    DESCBOMBA VARCHAR(50) NOT NULL);

ALTER TABLE BOMBAS
ADD CONSTRAINT PK_BOMBAS
PRIMARY KEY (ID);

COMMIT WORK;

ALTER TABLE BOMBAS
ADD CONSTRAINT FK_BOMBAS_1
FOREIGN KEY (ID_TANQUE)
REFERENCES TANQUES(ID)
ON UPDATE CASCADE;

COMMIT WORK;

CREATE TABLE ABASTECIMENTOS (
    ID INTEGER NOT NULL,
    ID_BOMBA INTEGER NOT NULL,
    DIA DATE NOT NULL,
    LITROS NUMERIC(15,2) DEFAULT 0 NOT NULL,
    VALOR NUMERIC(15,2) DEFAULT 0 NOT NULL,
    ALIQUOTA NUMERIC(15,2) DEFAULT 0 NOT NULL,
    IMPOSTO NUMERIC(15,2) DEFAULT 0 NOT NULL);

ALTER TABLE ABASTECIMENTOS
ADD CONSTRAINT PK_ABASTECIMENTOS
PRIMARY KEY (ID);

COMMIT WORK;

ALTER TABLE ABASTECIMENTOS
ADD CONSTRAINT FK_ABASTECIMENTOS_1
FOREIGN KEY (ID_BOMBA)
REFERENCES ABASTECIMENTOS(ID)
ON UPDATE CASCADE;

COMMIT WORK;
